/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borne;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font; 
import java.awt.event.ActionEvent; 
import java.awt.event.ActionListener;
import java.io.IOException; 
import java.sql.SQLException; 
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author kadhem
 */
public class Jborne extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form NewJFrame
     */
     private JTextField jtextTime;
     String str ="Lundi, mardi, mercredi et jeudi:Séance matinale: De 08H30 à 12H30  Séance de l'après-midi: De 13H30 à 17H30            ";
     String str2="       الاثنين، الثلاثاء، الأربعاء والخميس: الفترة الصباحية: من 8:30 حتي 12:30 دورة بعد الظهر: من 13:30 حتي 17:30";
    public Jborne() {
        initComponents();
         Thread t = new Thread(this);
         t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jpanelb1 = new borne.JpanelService();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        try {
            jpanelActualités1 = new borne.JpanelActualités();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        } catch (java.io.IOException e2) {
            e2.printStackTrace();
        }
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jClock1 = new borne.JClock();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenue");
        setBackground(new java.awt.Color(0, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        jpanelb1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpanelb1.setOpaque(false);
        getContentPane().add(jpanelb1);
        jpanelb1.setBounds(350, 260, 610, 310);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recette des finances Av. Med. Mâarouf                                                                                                           القباضـة الماليّـة شارع محمّد معروف بسوســة   ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 100, 1000, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/ENTETE BORNE - Copie.png"))); // NOI18N
        jLabel2.setText("MARHABA");
        jLabel2.setFocusCycleRoot(true);
        jLabel2.setFocusTraversalPolicyProvider(true);
        jLabel2.setVisible(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1010, 100);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(630, 238, 180, 110);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(320, 250, 90, 340);

        jLabel4.setText("BIENVENU");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(654, 20, 280, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("choisissez un service                                 خَدَماتٍ                  ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 220, 580, 30);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(970, 240, 60, 350);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(320, 590, 650, 20);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Tunisia-icon.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(930, 230, 80, 14);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/France-flat-icon.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 230, 34, 14);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(680, 0, 250, 100);

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(760, 40, 40, 14);

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("       الاثنين  ،  الثلاثاء  ،  الأربعاء   و الخميس:  الفترة الصباحية :  من  8:30   حتي 12:30  دورة  بعد الظهر: من    13:30  حتي 17:30");
        jLabel12.setAlignmentX(111.0F);
        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 660, 840, 40);

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("توقيت العمل");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(840, 660, 130, 40);

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/jouer-a-droite-fleche-icone-6822-32.png"))); // NOI18N
        jLabel16.setText("Horaire du travail");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 620, 150, 40);

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Lundi, mardi, mercredi et jeudi:Séance matinale: De 08H30 à 12H30  Séance de l'après-midi: De 13H30 à 17H30");
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(150, 620, 850, 40);

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/jouer-a-gauche-fleche-icone-6822-32.png"))); // NOI18N
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel18);
        jLabel18.setBounds(960, 660, 40, 40);

        jpanelActualités1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jpanelActualités1.setOpaque(false);
        getContentPane().add(jpanelActualités1);
        jpanelActualités1.setBounds(20, 260, 290, 310);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Actualités");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 160, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/news.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 220, 40, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("اخبارو معلومات  ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(180, 230, 100, 20);

        DateFormat dateFormat = new SimpleDateFormat("ddMMMyyyy",Locale.FRANCE);
        Calendar cal = Calendar.getInstance();
        String s=dateFormat.format(cal.getTime());
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText(s);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 93, 17);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/bleu.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(-20, 200, 1020, 500);

        jLabel14.setOpaque(true);

        jLabel20.setOpaque(true);

        javax.swing.GroupLayout jClock1Layout = new javax.swing.GroupLayout(jClock1);
        jClock1.setLayout(jClock1Layout);
        jClock1Layout.setHorizontalGroup(
            jClock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClock1Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jClock1Layout.setVerticalGroup(
            jClock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClock1Layout.createSequentialGroup()
                .addGroup(jClock1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jClock1);
        jClock1.setBounds(220, 150, 370, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/finances2.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(800, 110, 130, 109);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(390, 140, 210, 10);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(390, 200, 220, 10);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/1458320500_Home01.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 140, 65, 41);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Jborne p=new Jborne();

        p.getContentPane().setPreferredSize(new Dimension(650,400));
        p.pack();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jborne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jborne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jborne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jborne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jborne().setVisible(true);
                
                
            }
        });
    } 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private borne.JClock jClock1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private borne.JpanelActualités jpanelActualités1;
    private borne.JpanelService jpanelb1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
         while(true){
        char c = str.charAt(0);
        String rest = str.substring(1);
        str = rest + c;
        jLabel17.setText(str);
        char c2=str2.charAt(0);
        String rest2 = str2.substring(1);
        str2 = rest2+c2;
        jLabel12.setText(str2);
        try{
            Thread.sleep(130);
        }catch(InterruptedException e){ e.printStackTrace();}
    } //To change body of generated methods, choose Tools | Templates.
    }
}
 class ClockListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            
            
        } 

   
   
    }
