/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borne; 

import JDBC.Connect;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * 
 * @author kadhem
 */
public class JpanelActualités2 extends javax.swing.JPanel {

    /**  
     * Creates new form JpanelActualités2
     */
    String textFRF="";
    String textARF="";
     String[] splitArrayFR = null;
     String[] splitArrayAR = null;
    ResultSet rs=null;
    ResultSet rs2=null;
    PreparedStatement ps=null;
    public int id;
    String titreFR;
    String titreAR;
    String textFR;
    String textAR;
    int ids;
    public JpanelActualités2(int id) throws SQLException {
        initComponents();
        this.id=id;
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void myInitComponents() throws SQLException {
      Connection con=Connect.conDB();
       String sql="SELECT id_s_actualite,`titreAR_sactualite`, `titreFR_sactualite`, `id_actualite`, `textAR_sactualite`, `textFR_sactualite` FROM `s_actualite` WHERE id_actualite="+id;
        ps=con.prepareStatement(sql);
        rs = ps.executeQuery();
        
         setLayout(new java.awt.GridLayout(4,4,10,10));
        while(rs.next()){
             titreFR=rs.getString("titreFR_sactualite");
            // System.out.println(titreFR);
            ids=rs.getInt("id_s_actualite");
             titreAR=rs.getString("titreAR_sactualite");
            textAR=rs.getString("textAR_sactualite");
            textFR=rs.getString("textFR_sactualite"); 
            System.out.println(ids);
            // System.out.print(textAR);
            JButton b = new JButton(titreFR+" "+titreAR);
          // splitArrayFR = textFR.split(",");
          // splitArrayAR = textAR.split(",");
            b.setPreferredSize(new Dimension(700, 40));
             b.addActionListener(new java.awt.event.ActionListener() {
                 public void actionPerformed(java.awt.event.ActionEvent e) {  
                     System.out.println(ids);
                     String Newligne=System.getProperty("line.separator");
                     JOptionPane.showMessageDialog(null,textFR+Newligne+textAR);
                   
                    
                    
                    
                }
             });
//To change body of generated methods, choose Tools | Templates.
    add(b);}
}
}
