/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borne;

import JDBC.Connect;
import admin.Jactualite;
import entity.Client;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import borne.JpanelService;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author kadhem
 */
public class JpanelActualités extends javax.swing.JPanel {

    /**
     * Creates new form JpanelActualités
     */ 
     ResultSet rs=null;
    ResultSet rs2=null;
    PreparedStatement ps=null;
    public JpanelActualités() throws SQLException, IOException {
        initComponents();
         myInitComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents() throws SQLException, IOException {
       Connection con=Connect.conDB();
       String sql="SELECT id_actualite,titreAR_actualite,titreFR_actualite FROM `actualite`";
        ps=con.prepareStatement(sql);
        rs = ps.executeQuery();
        
         setLayout(new java.awt.GridLayout(4,4,10,10));
        while(rs.next()){
            String titreFR=rs.getString("titreFR_actualite");
            String titreAR=rs.getString("titreAR_actualite");
            int id = rs.getInt("id_actualite");
            JButton b = new JButton(titreFR+" "+titreAR);
             Font type = new Font("Arial",Font.BOLD,12);
               b.setFont(type);
            
            b.setPreferredSize(new Dimension(500, 40));
             b.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    try { 
                        removeAll();
                        repaint();
                        revalidate();
                        setLayout(new java.awt.GridLayout(1,3,5,5));
                        setLayout(null);
                        JpanelActualités2 jl=new JpanelActualités2(id);
                         jl.setVisible(true);
                         jl.setSize(260,260);
                         jl.setOpaque(false);
                         add(jl);
                    } catch (Exception ex) {
                        Logger.getLogger(JpanelService.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            add(b);  
            
            
            
        }
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
