/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package borne;

import JDBC.Connect;
import entity.Client;
import entity.Service;
import static entity.Statistique_1_.date;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.swing.JButton;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author kadhem
 */
public class JpanelService extends javax.swing.JPanel {
   @PersistenceContext(unitName = "adminPU")
    private EntityManager em;
    
      
    ResultSet rs=null;
    ResultSet rs2=null;
    PreparedStatement ps=null;
    ArrayList <Service> list=  new ArrayList <Service>();
    public JpanelService() throws SQLException {
      
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents() throws SQLException {
        
         Connection con=Connect.conDB();
         String sql="SELECT id_service FROM `service_has_guichet`";
        ps=con.prepareStatement(sql);
        rs = ps.executeQuery();
        int i=1;
        while(rs.next()){
            
             int id=rs.getInt(1);
            
                  rs.absolute(i++);
           ps=con.prepareStatement("SELECT nomFR,nomAR FROM `service` WHERE id_service= ?");
           ps.setInt(1,id);
          
            rs2 = ps.executeQuery();
            int j=1;
            //boucle pour recuperer les noms AR et FR des servies
              while(rs2.next()){
              String nomFR=rs2.getString("nomFR");
              String nomAR=rs2.getString("nomAR");
          
                list.add(new Service(id,nomAR,nomFR,1));
              }
              
              
         
        }
        setLayout(new java.awt.GridLayout(2,3,30,30));
        for(Service s:list){
            //System.out.println("JFRAME"+s.getNomFR());
             String Newligne=System.getProperty("line.separator"); 
            JButton b = new JButton(s.getNomFR()+Newligne+s.getNomAR());
            Font type = new Font("Arial",Font.BOLD,13);
               b.setFont(type);
             b.setPreferredSize(new Dimension(40,40));
             b.setBackground(Color.LIGHT_GRAY);;
            
           
            b.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    try {
                        Client c=new Client();
                         
                        
                        System.out.println(s.getIdService());
                        java.sql.Date sqlStartDate = new java.sql.Date( new Date().getTime());
                      
                       
                         
                      ps=con.prepareStatement("INSERT INTO `client`(`tmpArrive`, `id_service`) VALUES (?,?)");
                      ps.setDate(1,sqlStartDate);
                      ps.setInt(2,s.getIdService());
                      ps.executeUpdate();
                     String Newligne=System.getProperty("line.separator"); 
                      JOptionPane.showMessageDialog(null,"S'il vous plaît tirer le billet"+Newligne+"الرجاء سحب التذكرة");
                          
                    } catch (Exception ex) {
                        Logger.getLogger(JpanelService.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            add(b);
        }
    }

        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

