/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import JDBC.Connect;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kadhem
 */
public class JPSact extends javax.swing.JPanel {

    /**
     * Creates new form JPSact
     */
     private DefaultTableModel dt; 
    private int ida;
    private String titreAR,titreFr;
    private String textAR,textFR;
    int idm =0;
    //parametre de connexion 
    ResultSet rs=null;
    HashMap hm = new HashMap();
    PreparedStatement ps=null;
    public JPSact() throws SQLException {
        initComponents();
         myinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfr = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxfr = new javax.swing.JEditorPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxar = new javax.swing.JEditorPane();
        jLabel10 = new javax.swing.JLabel();
        Bmodifier = new javax.swing.JButton();
        Bactualiser = new javax.swing.JButton();
        Bsupprimer = new javax.swing.JButton();
        Bajouter = new javax.swing.JButton();

        setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/fianances.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(0, 80, 113, 143);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/finances2.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 10, 120, 73);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Recette des finances Av. Med. Mâarouf ");
        add(jLabel2);
        jLabel2.setBounds(210, 20, 306, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("القباضـة الماليّـة شارع محمّد معروف بسوســة");
        jLabel6.setToolTipText("");
        add(jLabel6);
        jLabel6.setBounds(230, 40, 259, 15);
        add(jSeparator2);
        jSeparator2.setBounds(170, 60, 410, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/1458320500_Home01.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(610, 10, 65, 41);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titre AR", "Titre FR", "Actualite P", "Texte FR", "Texte AR"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(160, 80, 452, 140);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Titre Français :");
        add(jLabel1);
        jLabel1.setBounds(50, 260, 90, 20);
        add(jtfr);
        jtfr.setBounds(150, 260, 290, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("titre Arabe:");
        add(jLabel3);
        jLabel3.setBounds(64, 300, 80, 14);

        jtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtarActionPerformed(evt);
            }
        });
        add(jtar);
        jtar.setBounds(150, 300, 290, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Actualite parent:");
        add(jLabel7);
        jLabel7.setBounds(34, 350, 100, 14);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(150, 350, 180, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Texte Français:");
        add(jLabel8);
        jLabel8.setBounds(44, 390, 90, 14);

        jScrollPane2.setViewportView(jtxfr);

        add(jScrollPane2);
        jScrollPane2.setBounds(150, 380, 190, 90);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Texte Arabe:");
        add(jLabel9);
        jLabel9.setBounds(340, 380, 90, 14);

        jScrollPane3.setViewportView(jtxar);

        add(jScrollPane3);
        jScrollPane3.setBounds(430, 380, 190, 90);

        DateFormat dateFormat = new SimpleDateFormat("ddMMMyyyy",Locale.FRANCE);
        Calendar cal = Calendar.getInstance();
        String s=dateFormat.format(cal.getTime());
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText(s);
        add(jLabel10);
        jLabel10.setBounds(40, 500, 80, 14);

        Bmodifier.setText("Modifier");
        Bmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodifierActionPerformed(evt);
            }
        });
        add(Bmodifier);
        Bmodifier.setBounds(310, 490, 73, 23);

        Bactualiser.setText("Actualiser");
        Bactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactualiserActionPerformed(evt);
            }
        });
        add(Bactualiser);
        Bactualiser.setBounds(389, 490, 90, 23);

        Bsupprimer.setText("Supprimer");
        Bsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsupprimerActionPerformed(evt);
            }
        });
        add(Bsupprimer);
        Bsupprimer.setBounds(480, 490, 90, 23);

        Bajouter.setText("Ajouter");
        Bajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajouterActionPerformed(evt);
            }
        });
        add(Bajouter);
        Bajouter.setBounds(570, 490, 69, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JPrincipale p=new JPrincipale();
        p.getContentPane().setPreferredSize(new Dimension(650,400));
        p.pack();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int i = jTable1.getSelectedRow(); // getSelectedRow() fonction nous retourne le ligne selectionner par l utilisateur

            Deplacer(i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur selectionnéé stg\n"+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodifierActionPerformed
        try {
            String titar=jtar.getText();
            String titfr=jtfr.getText();
            String txtar=jtxar.getText();
            String txtfr=jtxfr.getText();

            String stat=(String)jComboBox1.getSelectedItem();
            System.out.println(hm.get(stat));
            Connection con=Connect.conDB();
            ps=con.prepareStatement("UPDATE s_actualite  SET titreAR_sactualite=? , titreFR_sactualite=?,id_actualite=?,textAR_sactualite=?,textFR_sactualite=? WHERE id_s_actualite=?");
            ps.setString(1,titar);
            ps.setString(2,titfr);
            ps.setInt(3,(int) hm.get(stat));
            ps.setString(4,txtar);
            ps.setString(5,txtfr);
            ps.setInt(6,idm);
            ps.executeUpdate();
            jtfr.setText("");
            jtar.setText("");
            jtxfr.setText("");
            jtxar.setText("");
            dt.setRowCount(0);
            String Sql1 = "Select * From s_actualite";

            ps=con.prepareStatement(Sql1);
            rs = ps.executeQuery();

            System.out.println(rs);
            while(rs.next()){
                //System.out.println("kk");
                int id =  rs.getInt("id_actualite");
                System.out.println(id);
                titreAR = rs.getString("titreAR_sactualite");
                titreFr = rs.getString("titreFR_sactualite");
                textFR = rs.getString("textFR_sactualite");
                textAR = rs.getString("textAR_sactualite");
                Object[] stg = {titreAR,titreFr,id,textFR,textAR};
                dt.addRow(stg);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Jsactualite.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BmodifierActionPerformed

    private void BactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactualiserActionPerformed
        try {
            dt.setRowCount(0);
            String Sql1 = "Select * From s_actualite";
            Connection con=Connect.conDB();
            ps=con.prepareStatement(Sql1);
            rs = ps.executeQuery();

            System.out.println(rs);
            while(rs.next()){
                //System.out.println("kk");
                int id =  rs.getInt("id_actualite");
                System.out.println(id);
                titreAR = rs.getString("titreAR_sactualite");
                titreFr = rs.getString("titreFR_sactualite");
                textFR = rs.getString("textFR_sactualite");
                textAR = rs.getString("textAR_sactualite");
                Object[] stg = {titreAR,titreFr,id,textFR,textAR};
                dt.addRow(stg);
            }        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Jsactualite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BactualiserActionPerformed

    private void BsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsupprimerActionPerformed
        try {
            int id = 0;
            String titar=jtar.getText();
            String titfr=jtfr.getText();
            String txtar=jtxar.getText();
            String txtfr=jtxfr.getText();
            // String Sql = "Select id_s_actualite from s_actualite where titreAR_sactualite="+titar+"AND titreFR_sactualite="+titfr+" AND textAR_sactualite="+txtar+" AND textFR_sactualite="+txtfr;
            String sql1="SELECT id_s_actualite  FROM s_actualite WHERE titreAR_sactualite =?  AND titreFR_sactualite = ? ";
            Connection con=Connect.conDB();
            ps=con.prepareStatement(sql1);
            ps.setString(1,titar);
            ps.setString(2,titfr);
            // ps.setString(3,txtar);
            // ps.setString(4,txtfr);
            rs=ps.executeQuery();
            while(rs.next()){
                id=rs.getInt("id_s_actualite");
            }
            String sql2="DELETE FROM `s_actualite` WHERE id_s_actualite=?";
            ps=con.prepareStatement(sql2);
            ps.setInt(1,id);

            ps.executeUpdate();
            dt.setRowCount(0);
            String Sql1 = "Select * From s_actualite";

            ps=con.prepareStatement(Sql1);
            rs = ps.executeQuery();

            System.out.println(rs);
            while(rs.next()){
                //System.out.println("kk");
                int ids =  rs.getInt("id_actualite");
                System.out.println(ids);
                titreAR = rs.getString("titreAR_sactualite");
                titreFr = rs.getString("titreFR_sactualite");
                textFR = rs.getString("textFR_sactualite");
                textAR = rs.getString("textAR_sactualite");
                Object[] stg = {titreAR,titreFr,id,textFR,textAR};
                dt.addRow(stg);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Jsactualite.class.getName()).log(Level.SEVERE, null, ex);
        }
         jtfr.setText("");
            jtar.setText("");
            jtxfr.setText("");
            jtxar.setText("");
    }//GEN-LAST:event_BsupprimerActionPerformed

    private void BajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajouterActionPerformed
        try {
            String titar=jtar.getText();
            String titfr=jtfr.getText();
            String txtar=jtxar.getText();
            String txtfr=jtxfr.getText();

            String stat=(String)jComboBox1.getSelectedItem();
            System.out.println(hm.get(stat));
            Connection con=Connect.conDB();
            ps=con.prepareStatement("INSERT INTO `s_actualite`(`titreAR_sactualite`, `titreFR_sactualite`, `id_actualite`, `textAR_sactualite`, `textFR_sactualite`) VALUES (?,?,?,?,?)");
            ps.setString(1,titar);
            ps.setString(2,titfr);
            ps.setInt(3,(int) hm.get(stat));
            ps.setString(4,txtar);
            ps.setString(5,txtfr);
            ps.executeUpdate();
            int id=(int) hm.get(stat);
            Object[] stg = {titar,titfr,id,txtfr,txtar};
            dt.addRow(stg);
            jtfr.setText("");
            jtar.setText("");
            jtxfr.setText("");
            jtxar.setText("");// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Jsactualite.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BajouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bactualiser;
    private javax.swing.JButton Bajouter;
    private javax.swing.JButton Bmodifier;
    private javax.swing.JButton Bsupprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtar;
    private javax.swing.JTextField jtfr;
    private javax.swing.JEditorPane jtxar;
    private javax.swing.JEditorPane jtxfr;
    // End of variables declaration//GEN-END:variables
private void Afficher(){
          
   
     try{
        dt.setRowCount(0);
      String Sql = "Select * From s_actualite";
       Connection con=Connect.conDB();
       ps=con.prepareStatement(Sql);
       rs = ps.executeQuery();
        //dt.setRowCount(0); // vider la list des stagiaires.
       // rs = ps.executeQuery("Select * From s_actualite");
        System.out.println(rs);
        while(rs.next()){
            //System.out.println("kk");
           int id =  rs.getInt("titreAR_sactualite");
           System.out.println(id);
            titreAR = rs.getString("titreAR_sactualite");
            titreFr = rs.getString("titreFR_sactualite");
            textFR = rs.getString("textFR_sactualite");
            textAR = rs.getString("textAR_sactualite");
            Object[] jTab = {titreAR,titreFr,id,textFR,textAR};
            dt.addRow(jTab);
        }
    }catch(Exception e){
        //JOptionPane.showMessageDialog(null, "Erreur afficher la liste des stagiaire\n"+e.getMessage());
    }
    

}

   private void Deplacer(int i) throws SQLException{
   
        
        jtar.setText(dt.getValueAt(i, 0).toString()); 
        jtfr.setText(dt.getValueAt(i, 1).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        jtxar.setText(dt.getValueAt(i, 3).toString()); // lorseque i=1 getValueAt nous retourne le premier ligne si i=2 le ligne ......
       jtxfr.setText(dt.getValueAt(i,4).toString());
        //txtser.setSelectedItem(dt.getValueAt(i, 4).toString());
         String sql1="SELECT id_s_actualite  FROM s_actualite WHERE titreAR_sactualite =?  AND titreFR_sactualite = ? ";
            Connection con=Connect.conDB();
            ps=con.prepareStatement(sql1);
            ps.setString(1,jtar.getText());
            ps.setString(2,jtfr.getText());
            // ps.setString(3,txtar);
            // ps.setString(4,txtfr);
            rs=ps.executeQuery();
            while(rs.next()){
                idm=rs.getInt("id_s_actualite");
                System.out.println(idm);
            }   
      
    }

    private void myinit() throws SQLException {
         dt = new DefaultTableModel();// dt c'est un variable pour stocké les element d'un tableau {ligne et colomn}
      
        dt.addColumn("titreAR");
        dt.addColumn("titreFr");
        dt.addColumn("id");
        dt.addColumn("textFR");
        dt.addColumn("textAR");
        
       jTable1.setModel(dt);
        
       String Sql = "Select * from actualite ";
       Connection con=Connect.conDB();
             ps=con.prepareStatement(Sql);
             
             rs = ps.executeQuery();
             
              while(rs.next()){
               int ida=rs.getInt("id_actualite");
               String titre=rs.getString("titreFR_actualite");
               
               hm.put(titre,ida);
               }//To change body of generated methods, choose Tools | Templates.
              Set cles = hm.keySet();
              Iterator it = cles.iterator();
              while (it.hasNext()){
              Object cle = it.next();
              //System.out.println((String)hm.get(cle));
              jComboBox1.addItem((String)cle);
              
              // tu peux typer plus finement ici
}
             String Sql1 = "Select * From s_actualite";
 
       ps=con.prepareStatement(Sql1);
      rs = ps.executeQuery();

        System.out.println(rs);
        while(rs.next()){
            //System.out.println("kk");
           int id =  rs.getInt("id_actualite");
           System.out.println(id);
            titreAR = rs.getString("titreAR_sactualite");
            titreFr = rs.getString("titreFR_sactualite");
            textFR = rs.getString("textFR_sactualite");
            textAR = rs.getString("textAR_sactualite");
            Object[] stg = {titreAR,titreFr,id,textFR,textAR};
            dt.addRow(stg);
    } //To change body of generated methods, choose Tools | Templates.
    }
}
